### ISSUE TITLE
Use JSONPath style syntax for parameter list names

### ISSUE THREAD

**Issue by nncarlson** [nncarlson/petaca#17]
I'm using a wonky `->` as the separator between the parts of a parameter list name, and I don't recall why. Consider replacing this by [JSONPath](https://goessner.net/articles/JsonPath/) or [JSON Pointer](https://tools.ietf.org/html/rfc6901) style syntax.

**Comment by zbeekman** [comment]
JSONPath is probably more widely used, FWIW

**Comment by nncarlson** [comment]
That was my impression too from a bit of googling.
